import error
import io

try {
  None.field_on_none ; Will trigger an exception.
} catch e {
  io.fprintln(io.ERROR, e)
}

try {
  raise error.Error('Hello, world!')
} catch e {
  io.fprintln(io.ERROR, e)
}